version: "3"
services:
  api:
    container_name: vinopinionsapp-expo-test
    image: ghcr.io/layla-oskar-schule/vinopinionsapp-expo:staging
    networks:
      - server

networks:
  server:
    external: true
